apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "migrator.fullname" . }}
  labels:
    {{- include "migrator.labels" . | nindent 4 }}
data:
  {{- with .Values.config }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
