apiVersion: v2
name: shitpostbot
description: A Helm chart for Kubernetes
type: application
version: 0.0.0
appVersion: "1.0.0"
dependencies:
  - name: worker
    version: 0.0.0
  - name: migrator
    version: 0.0.0
  - name: ml-service
    version: 0.0.0
  - name: post-reevaluator
    version: 0.0.0
  - name: image-url-refresher
    version: 0.0.0
